package CiderCMS::Schema;

use strict;
use base qw/DBIx::Class::Schema/;

__PACKAGE__->load_namespaces;

=head1 NAME

CiderCMS::Schema - L<DBIx::Class::Schema::Loader> class

=head1 SYNOPSIS

See L<CiderCMS>

=head1 DESCRIPTION

Dynamic L<DBIx::Class::Schema::Loader> schema for use in L<CiderCMS::Model::Authentication>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Stefan Seifert

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
